### ISSUE TITLE
Encrypted content of NUS titles without cetk file on NUS does not download without local cetk file

### ISSUE THREAD

**Issue by htv04** [TheShadowEevee/Sharpii-NetCore#6]
I think the original Sharpii also had this bug (if this is considered one), only it was unavoidable because there was no local cetk support.

The encrypted content stored on the NUS does not download if a cetk file isn't present, even if the encrypt flag is set so that only the encrypted files download. Sharpii just throws this error:
```ERROR DETAILS: CETK Doesn't Exist and Downloading Ticket Failed:
The remote server returned an error: (404) Not Found.
Error: SHARPII_NET_CORE_NUSD_UNKNOWN_01
```
and errors out. However, having a cetk file of any kind in the destination directory avoids this issue, even if it's a dummy file.

**Comment by TheShadowEevee** [comment]
Yes, Version 1.1.3 adds support for local cetk files. libWiiSharp generally needs a cetk file when downloading from NUS, although I could see if I could modify it to only require the cetk if it needs it (I believe the 404 is from the cetk download attempt). There is the issue of having an "Incomplete" download without a cetk though.

**Comment by htv04** [comment]
Maybe Sharpii could "force-set" the -decrypt and -wad flags off if they're enabled and a CETK file can't be found or downloaded? This would make it so that Sharpii doesn't run into an error after bypassing the CETK file download error.

**Comment by TheShadowEevee** [comment]
It seems that even with -decrypt and -wad unset Sharpii still can't continue w/o the cetk file

**Comment by TheShadowEevee** [comment]
I am closing this for now as this seems to be really an unfixable server issue, if you have any other suggestions feel free to reply
