### ISSUE TITLE
OOM Error occurs when trying to extract big WADs

### ISSUE THREAD

**Issue by zurgeg** [TheShadowEevee/Sharpii-NetCore#8]
Tried with `Guitar Hero 5 - Taylor Swift - Our Song (USA) (GH 5).wad` (SHA256: `272BD9CD2433ABB707644D3650E5CD26D3D7F55AE853343B4A97011A915DFFB2`)

**Comment by TheShadowEevee** [comment]
Sorry, I missed this issue. I'll take a look when I can

**Comment by TheShadowEevee** [comment]
@zurgeg Actually can you try again using [v1.1.6.1](https://github.com/TheShadowEevee/Sharpii-NetCore/releases/tag/1.1.6.1)? Some quick tests on my side show a difference, wondering if things changed on your side.

**Comment by zurgeg** [comment]
> @zurgeg Actually can you try again using [v1.1.6.1](https://github.com/TheShadowEevee/Sharpii-NetCore/releases/tag/1.1.6.1)? Some quick tests on my side show a difference, wondering if things changed on your side.

Will try in a little bit, thanks

**Comment by TheShadowEevee** [comment]
No rush, just checking in to see if there's been an update since it's been a bit. This is a fairly long standing issue so I'm hoping this does solve it!

**Comment by TheShadowEevee** [comment]
I'm closing this for now; if you have more information feel free to respond back and if need be the issue can be reopened

**Comment by zurgeg** [comment]
@TheShadowEevee Problem solved! TYSM!
