### ISSUE TITLE
tried to send a wad and this happens

### ISSUE THREAD

**Issue by libewa** [TheShadowEevee/Sharpii-NetCore#9]
```
> .\Sharpii.exe SendWad -ip 192.168.178.31 -dol '.\WAD\Everybody Votes Channel (Europe) (Channel) (RiiConnect24).wad'
ERROR: WadInstaller.dll not found
This should not appear on the .Net Core port.
If you see this, report how you got here on https://github.com/TheShadowEevee/Sharpii-NetCore/issues.
Error: SHARPII_NET_CORE_HBC_MISSING_DLL_WADINSTALLER
```

**Comment by TheShadowEevee** [comment]
Try https://github.com/TheShadowEevee/Sharpii-NetCore/releases/tag/v1.1.10 and see if it works better. An old error check from a couple versions ago was never actually removed and was triggering here.

As for the command, try `.\Sharpii.exe SendWad -ip 192.168.178.31 -wad '.\WAD\Everybody Votes Channel (Europe) (Channel) (RiiConnect24).wad'`. The help text was slightly incorrect before and didn't actually show this as an option very well.

**Comment by TheShadowEevee** [comment]
I believe this issue is fixed in the newest release. If you continue having problems, please reopen this issue or open a new issue with details. Thank you!
